### ISSUE TITLE
Possibly provide a patch?

### ISSUE THREAD

**Issue by Earnestly** [MyrtleSoftware/glibc-no-lock-elision#1]
Why not provide a simple patch that everyone can use instead of depending on Debian's infrastructure?

Edit: Oh, this appears to be literally a one line compile-time configuration, yet this is an enitre clone of glibc?  ... nevermind.

**Comment by expipiplus1** [comment]
Yeah, it's nothing complicated. The source code is mirrored here for anyone who doesn't want to make that change and grab the source. The hardest part of this easy task is packaging and installing this, hence the debian packaging focus.

As for submitting a patch, lock elision is actually a good feature to have on generally.
