### ISSUE TITLE
Same issue in D2XX

### ISSUE THREAD

**Issue by jakobwenzel** [MyrtleSoftware/glibc-no-lock-elision#2]
Hi, 

first of all, thanks for the work in figuring this out. This is not a real issue but more of a dump of relevant keywords so that other people may find a solution to another crash:

The D2XX driver for some FTDI chips (http://www.ftdichip.com/Drivers/D2XX.htm) seems to have the very same problem. It crashes with this Stack Trace:

> #0  __lll_unlock_elision (lock=0x7fffd8000de8, private=0) at ../sysdeps/unix/sysv/linux/x86/elision-unlock.c:29
> #1  0x00007fffe5ef812f in EventDestroy (pE=0x7fffd8000de8) at Event.c:28
> #2  0x00007fffe5ef257e in FT_Close (ftHandle=0x7fffd8000ae0) at ftd2xx.c:1813
> #3  0x00007fffe6354d1d in LIBFTD2XX::Close(void*) () from /usr/local/lib64/digilent/adept/libdpcomm.so.2
> #4  0x00007fffe6351ae6 in FTDIC::FEnumAndUpdateCache() () from /usr/local/lib64/digilent/adept/libdpcomm.so.2
> #5  0x00007fffe634fb73 in FTDIC::FEnum(int, int, unsigned int, void*, DVCMG*) () from /usr/local/lib64/digilent/adept/libdpcomm.so.2
> #6  0x00007fffe634deec in ENMMG::DoEnumThread() () from /usr/local/lib64/digilent/adept/libdpcomm.so.2
> #7  0x00007fffe634d499 in EnumThread(void*) () from /usr/local/lib64/digilent/adept/libdpcomm.so.2
> #8  0x00007fffeea1f70a in start_thread (arg=0x7fffdffff700) at pthread_create.c:333
> #9  0x00007fffee03582d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Observed in Xilinx Impact while trying to program a Nexys Video, and in my own programs.

It would be great if you could add that Info to the Readme :)

Cheers,
Jakob

**Comment by expipiplus1** [comment]
Thanks,

I've added this information to the readme.
